//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string ActionCloseMobileNavButton {
            get {
                return ResourceManager.GetString("ActionCloseMobileNavButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksportuj do CSV.
        /// </summary>
        public static string ActionExportToCSV {
            get {
                return ResourceManager.GetString("ActionExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string ActionLoginButton {
            get {
                return ResourceManager.GetString("ActionLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string ActionRegisterButton {
            get {
                return ResourceManager.GetString("ActionRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string DashboardENButton {
            get {
                return ResourceManager.GetString("DashboardENButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        public static string DashboardPLButton {
            get {
                return ResourceManager.GetString("DashboardPLButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        public static string LabelForAmount {
            get {
                return ResourceManager.GetString("LabelForAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string LabelForComeName {
            get {
                return ResourceManager.GetString("LabelForComeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelForEmail {
            get {
                return ResourceManager.GetString("LabelForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezent.
        /// </summary>
        public static string LabelForGiftType {
            get {
                return ResourceManager.GetString("LabelForGiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string LabelForIncomeType {
            get {
                return ResourceManager.GetString("LabelForIncomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string LabelForName {
            get {
                return ResourceManager.GetString("LabelForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string LabelForPassword {
            get {
                return ResourceManager.GetString("LabelForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie !.
        /// </summary>
        public static string LabelForRememberMe {
            get {
                return ResourceManager.GetString("LabelForRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string LabelForRepeatPassword {
            get {
                return ResourceManager.GetString("LabelForRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłata.
        /// </summary>
        public static string LabelForSalaryType {
            get {
                return ResourceManager.GetString("LabelForSalaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oszczędności.
        /// </summary>
        public static string LabelForSavingType {
            get {
                return ResourceManager.GetString("LabelForSavingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptuję regulamin.
        /// </summary>
        public static string LabelForTermsAndConditions {
            get {
                return ResourceManager.GetString("LabelForTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adres email jest już zajęty!.
        /// </summary>
        public static string MessageForAlreadyExistingEmail {
            get {
                return ResourceManager.GetString("MessageForAlreadyExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas dodawania wpływu... Przepraszamy..
        /// </summary>
        public static string MessageForErrorIncomeSaving {
            get {
                return ResourceManager.GetString("MessageForErrorIncomeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy adres email!.
        /// </summary>
        public static string MessageForErrorIncorrectEmail {
            get {
                return ResourceManager.GetString("MessageForErrorIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła nie są takie same!.
        /// </summary>
        public static string MessageForErrorMatchingPasswords {
            get {
                return ResourceManager.GetString("MessageForErrorMatchingPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas dodawania wydatku... Przepraszamy..
        /// </summary>
        public static string MessageForErrorOutcomeSaving {
            get {
                return ResourceManager.GetString("MessageForErrorOutcomeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nietak. Odśwież stronę i spróbuj ponownie!.
        /// </summary>
        public static string MessageForErrorRegister {
            get {
                return ResourceManager.GetString("MessageForErrorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj adres email!.
        /// </summary>
        public static string MessageForErrorRequiredEmail {
            get {
                return ResourceManager.GetString("MessageForErrorRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj swoje imię!.
        /// </summary>
        public static string MessageForErrorRequiredName {
            get {
                return ResourceManager.GetString("MessageForErrorRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj hasło!.
        /// </summary>
        public static string MessageForErrorRequiredPassword {
            get {
                return ResourceManager.GetString("MessageForErrorRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby kontynuować, musisz zaakceptować regulamin!.
        /// </summary>
        public static string MessageForErrorRequiredTerms {
            get {
                return ResourceManager.GetString("MessageForErrorRequiredTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny email lub hasło.
        /// </summary>
        public static string MessageForInvalidLogin {
            get {
                return ResourceManager.GetString("MessageForInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła nie są takie same!.
        /// </summary>
        public static string MessageForNotTheSamePasswords {
            get {
                return ResourceManager.GetString("MessageForNotTheSamePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpływ został zapisany..
        /// </summary>
        public static string MessageForSuccessIncomeSaving {
            get {
                return ResourceManager.GetString("MessageForSuccessIncomeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatek został zapisany..
        /// </summary>
        public static string MessageForSuccessOutcomeSaving {
            get {
                return ResourceManager.GetString("MessageForSuccessOutcomeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string TextForAdding {
            get {
                return ResourceManager.GetString("TextForAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wpływ.
        /// </summary>
        public static string TextForAddingIncome {
            get {
                return ResourceManager.GetString("TextForAddingIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wydatek.
        /// </summary>
        public static string TextForAddingOutcome {
            get {
                return ResourceManager.GetString("TextForAddingOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień walutę.
        /// </summary>
        public static string TextForChangingCurrency {
            get {
                return ResourceManager.GetString("TextForChangingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień język.
        /// </summary>
        public static string TextForChangingLanguage {
            get {
                return ResourceManager.GetString("TextForChangingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecnie.
        /// </summary>
        public static string TextForCurrent {
            get {
                return ResourceManager.GetString("TextForCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykresy.
        /// </summary>
        public static string TextForDashboardGraphs {
            get {
                return ResourceManager.GetString("TextForDashboardGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpływy.
        /// </summary>
        public static string TextForDashboardIncomes {
            get {
                return ResourceManager.GetString("TextForDashboardIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatki.
        /// </summary>
        public static string TextForDashboardOutcomes {
            get {
                return ResourceManager.GetString("TextForDashboardOutcomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz już konto?.
        /// </summary>
        public static string TextForHavingAccountAlready {
            get {
                return ResourceManager.GetString("TextForHavingAccountAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpływy.
        /// </summary>
        public static string TextForIncome {
            get {
                return ResourceManager.GetString("TextForIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota wpływu.
        /// </summary>
        public static string TextForIncomeAmount {
            get {
                return ResourceManager.GetString("TextForIncomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wejścia.
        /// </summary>
        public static string TextForIncomeInsertTime {
            get {
                return ResourceManager.GetString("TextForIncomeInsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa wpływu.
        /// </summary>
        public static string TextForIncomeName {
            get {
                return ResourceManager.GetString("TextForIncomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ wpływu.
        /// </summary>
        public static string TextForIncomesType {
            get {
                return ResourceManager.GetString("TextForIncomesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogólne.
        /// </summary>
        public static string TextForNavDashboard {
            get {
                return ResourceManager.GetString("TextForNavDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz jeszcze konta ? .
        /// </summary>
        public static string TextForNotHavingAccountYet {
            get {
                return ResourceManager.GetString("TextForNotHavingAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatki.
        /// </summary>
        public static string TextForOutcome {
            get {
                return ResourceManager.GetString("TextForOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwoda wydatku.
        /// </summary>
        public static string TextForOutcomeAmount {
            get {
                return ResourceManager.GetString("TextForOutcomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wyjścia.
        /// </summary>
        public static string TextForOutcomeInsertTime {
            get {
                return ResourceManager.GetString("TextForOutcomeInsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa wydatku.
        /// </summary>
        public static string TextForOutcomeName {
            get {
                return ResourceManager.GetString("TextForOutcomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ wydatku.
        /// </summary>
        public static string TextForOutcomesType {
            get {
                return ResourceManager.GetString("TextForOutcomesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaoszczędzone.
        /// </summary>
        public static string TextForSaved {
            get {
                return ResourceManager.GetString("TextForSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string TextForSettings {
            get {
                return ResourceManager.GetString("TextForSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykresy.
        /// </summary>
        public static string TitleForDashboardGraphs {
            get {
                return ResourceManager.GetString("TitleForDashboardGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podsumowanie.
        /// </summary>
        public static string TitleForDashboardSummary {
            get {
                return ResourceManager.GetString("TitleForDashboardSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string TitleForDashboardTitle {
            get {
                return ResourceManager.GetString("TitleForDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menedżer Finansów.
        /// </summary>
        public static string TitleForTheApp {
            get {
                return ResourceManager.GetString("TitleForTheApp", resourceCulture);
            }
        }
    }
}
